# Generated by Django 4.0.5 on 2022-06-15 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=1, null=True)),
                ('prefix', models.CharField(choices=[('Mr', 'Mister'), ('Mrs', 'Mistress'), ('Ms', 'Missus')], max_length=10, null=True)),
                ('suffix', models.CharField(choices=[('Jr', 'Junior'), ('Sr', 'Senior'), ('II', 'Second'), ('III', 'Third'), ('IV', 'Fourth')], max_length=10, null=True)),
                ('pronouns', models.CharField(choices=[('He', 'He/Him/His'), ('She', 'She/Her/Hers'), ('They', 'They/Them/Theirs')], max_length=25, null=True)),
                ('verbal_password', models.CharField(max_length=100)),
                ('ssn', models.IntegerField(validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(999999999)])),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField(null=True)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=25)),
                ('zip_code', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('home_number', models.IntegerField(null=True)),
                ('mobile_number', models.IntegerField(null=True)),
                ('work_number', models.IntegerField(null=True)),
            ],
        ),
    ]
