# Generated by Django 4.0.5 on 2022-06-16 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='home_number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000)]),
        ),
        migrations.AlterField(
            model_name='member',
            name='middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile_number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000)]),
        ),
        migrations.AlterField(
            model_name='member',
            name='work_number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000)]),
        ),
    ]
