# Generated by Django 4.0.5 on 2022-06-16 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_member_home_number_alter_member_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='home_number',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile_number',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='member',
            name='work_number',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
