# Generated by Django 4.0.5 on 2022-06-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_member_home_number_alter_member_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
